spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sunglowsys
    username: postgres
    password: postgres


  jpa:
    show-sql: true

    hibernate:
      dialect: org.hibernate.dialect.PostgresSQLDialect
      ddl-auto: update
